interface CloudflareEnv {
  ATTACHMENT_STORAGE_ENDPOINT?: string;
  ATTACHMENT_STORAGE_BUCKET?: string;
  ATTACHMENT_STORAGE_REGION?: string;
  ATTACHMENT_STORAGE_ACCESS_KEY_ID?: string;
  ATTACHMENT_STORAGE_SECRET_ACCESS_KEY?: string;
}
